name: validate-pr
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited  # do not remove, this executes when someone fixes the PR title
    branches:
      - man

jobs:
  validate:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: self-hosted
    steps:
      - name: Validate PR title prefix
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "validating PR title: $title"
          regex="^(fix|feat|chore|refactor|build|ci|docs|revert|style|test)(\([a-zA-Z0-9-]+\))?(!)?: .+"
          if [[ ! $title =~ $regex ]]; then
            echo "::error title=Pull request title does not have the required prefix"
            exit 1
          fi
